### ISSUE TITLE
doesn't work in Chrome!

### ISSUE THREAD

**Issue by tamassy** [toddpress/Unicorn-js#4]
Hi i know this is a quite old js, but i think it's really functional.
why the demo is not working in Firefox?
http://lab.tamassy.co.uk/rainbow-link/01_js/
there is any new version coming out?

**Comment by toddpress** [comment]
Sorry, I haven't kept up with this repo lately. It seems it may be too little, too late-- But this seems to be working in Chromium, anyway-- Right here: http://xoxco.com/projects/code/rainbow/

And yes, I think that I'm going to do another release to correct the current issues  and hopefully improve the api. @tamassy Do you have any suggestions of features that you feel would enhance your experience with unicorn-- just picking your brain for features, etc... If you can DM me on here, do that; otherwise, hit me up right here when your able (on a different issue-- closing current)
